name: '${project_name}'
version: '${version}'
author: '${authors}'
description: '${project_description}'
website: '${homepage_url}'
main: '${group}.platforms.BukkitPlugin'
depends: [TaterLib ]
softdepends: [ LuckPerms ]
folia-supported: true
