name: '${project_name}'
version: '${version}'
author: '${authors}'
description: '${project_description}'
website: '${homepage_url}'
main: 'dev.neuralnexus.taterloader.platforms.BukkitLoaderPlugin'
depends: [ ]
softdepends: [ LuckPerms ]
folia-supported: true
