# https://files.minecraftforge.net/net/minecraftforge/forge/
modLoader = "javafml"
loaderVersion = "[38,)"
license = "GPL-3"
issueTrackerURL="https://github.com/p0t4t0sandwich/TaterLib/issues"

[[mods]]
modId = "taterlib"
version = "${file.jarVersion}"
displayName = "TaterAPI"
updateJSONURL="https://raw.githubusercontent.com/p0t4t0sandwich/TaterLib/main/forgeUpdates.json"
displayURL="https://github.com/p0t4t0sandwich/TaterLib"
logoFile= "../TaterLib.png"
credits="p0t4t0sandwich"
authors="p0t4t0sandwich"
displayTest="IGNORE_SERVER_VERSION"
description = '''
A cross API code library for various generalizations used in the Tater* plugins
'''

# Forge Dependency
[[dependencies.taterlib]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

# Minecraft Dependency
[[dependencies.taterlib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
ordering = "NONE"
side = "BOTH"

# LuckPerms Dependency
[[dependencies.taterlib]]
modId = "luckperms"
mandatory = false
versionRange = "[5.3,)"
ordering = "NONE"
side = "SERVER"
