name: TaterAPI
version: '${version}'
author: p0t4t0sandwich
description: A cross API code library for various generalizations used in the Tater* plugins
main: dev.neuralnexus.taterapi.bukkit.BukkitTaterAPIPlugin
depend: []
softdepend: [LuckPerms]
folia-supported: true
commands:
  taterapi:
    description: TaterAPI command
    usage: /taterapi <reload|version>
    permission: taterapi.command
