name: Bug report
description: Create a report to help TaterLib improve
labels: 'bug'
body:
  - type: textarea
    attributes:
      label: Debug Information
      description: Please run `/taterlib dump` (or `/taterlib fulldump` for some extra mod/plugin info) and paste the output here (debug output is also in `logs/taterlib-dump.json`).
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description of behavior
      description: A clear and concise description of what the bug is, including what you expected to happen and what actually happened.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Reproduction Steps
      value: |
        Steps to reproduce the behavior:
        1. Use above version of TaterLib and server software with mod "someMod"
        2. Run the server/start a world
        3. Something happens, error occurs, etc.
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs
      description: |
        Include the full client/server/proxy logs e.g. `logs/latest.log`, `logs/debug.log`, and `crash-reports/*.txt` (upload
        them all if applicable). Use a paste site like https://mclo.gs (use (GitHub Gists)[https://gist.github.com] if the
        logs are too long). Do not paste them directly into the issue. If you trim the logs, you will not receive support.
    validations:
      required: true
  - type: textarea
    attributes:
      label: TaterLib Configuration
      description: Include your `taterlib.toml` file (omit sensitive information)
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here (e.g. screenshots, clips, etc.)
    validations:
      required: false
