# https://files.minecraftforge.net/net/minecraftforge/forge/
modLoader = "javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/p0t4t0sandwich/TaterLib/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/p0t4t0sandwich/TaterLib/main/forgeUpdates.json"
displayURL="https://github.com/p0t4t0sandwich/TaterLib"
logoFile="${mod_name}.png"
credits="${mod_authors}"
authors="${mod_authors}"
displayTest="IGNORE_SERVER_VERSION"
description = '''${mod_description}'''

# Forge Dependency
[[dependencies.${mod_id}]]
modId = "forge"
mandatory = false
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

# NeoForge Dependency
[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = false
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

# Minecraft Dependency
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

# LuckPerms Dependency
[[dependencies.${mod_id}]]
modId = "luckperms"
mandatory = false
versionRange = "[5.3,)"
ordering = "NONE"
side = "SERVER"
