name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache gradle caches
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/settings.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-caches

      - name: Cache gradle wrapper
        uses: actions/cache@v4
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/settings.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-wrapper

      - name: Setup
        run: ./gradlew setup

      - name: Build
        run: ./gradlew build

      - name: View files
        run: ls -l target

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: taterlib
          compression-level: 0 # .jar files are already compressed anyway
          path: target/Taterlib-*.jar