# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Cache Gradle User Files
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-user-home
      - name: Cache Gradle Files
        uses: actions/cache@v1
        with:
          path: ./.gradle
          key: ${{ runner.os }}-gradle-file
#      - name: Grant execute permission for gradlew and build.sh
#        run: chmod +x gradlew build.sh
#      - name: Build
#        run: |
#          ./gradlew build
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build
      - name: Sketch Build
        run: |
          ./build.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: TaterLib
          path: ./target/*
